# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdb', '0002_auto_20161108_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating0',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating1',
            field=models.IntegerField(),
        ),
    ]
