# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdb', '0003_auto_20161108_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.CharField(default='UFSM', max_length=200),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating0',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating1',
            field=models.IntegerField(default=0),
        ),
    ]
