# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdb', '0004_auto_20161118_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
    ]
