# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdb', '0008_auto_20161118_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbToken', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webdb.Login'),
            preserve_default=False,
        ),
    ]
